### PR TITLE
Updating LD_LIBRARY_PATH for tf-2.0 Dockerfile.gpu

### PR DESCRIPTION
**Pull request by preshen-goobiah**
*Issue #, if available:* 
Running tf.summary.trace_on() with TensorFlow 2.0 results in:

> Could not load dynamic library 'libcupti.so.10.0'; dlerror: libcupti.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64. 

libcupti.so.10.0 can be found in `/usr/local/cuda/extras/CUPTI/lib64` , we can prepend the location to `LD_LIBRARY_PATH`. 

*Description of changes:*
Change `ENV LD_LIBRARY_PATH` to include `/usr/local/cuda/extras/CUPTI/lib64` in tf-2.0.0 Dockerfile.gpu

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by codewithsk** [comment]
@preshen-goobiah Please review the build failure and update your branch.

**Comment by preshen-goobiah** [comment]
@codewithsk Thanks, please may you review.

**Comment by codewithsk** [comment]
Thank you for your contribution. LGTM. Does this change need to be added to 2.1 too?

**Comment by preshen-goobiah** [comment]
@codewithsk  Cool, I changed it for 2.1 too. Please review.

**Comment by codewithsk** [comment]
LGTM! Branch was out of date with tf-2 branch. I"m updating it. Once the build passes this can be merged.

**Pull request merged**
