### PR TITLE
fix: use default region when network is not available.

### PR DESCRIPTION
**Pull request by mvsusp**
*Description of changes:*
- use default region when network is not available.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://8teunz1x41.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=27bb1788-cdee-4e17-8b74-31e8a98e746d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://8teunz1x41.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d6b041c8-5809-481b-aa70-56cb17497f45%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://8teunz1x41.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=759d0f17-772b-43da-9b50-4d8d0f91b382%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by laurenyu** [comment]
closing due to inactivity. also, the change in base branch really messed up the diff 😂

**Pull request closed without merging**
