### PR TITLE
change: install SageMaker Python SDK into Python 3 images - TF 2.1.0

### PR DESCRIPTION
**Pull request by laurenyu**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by codewithsk** [comment]
@laurenyu Looks like there are some merge conflicts. I can mege them once the conflicts have been resolved.

**Comment by laurenyu** [comment]
@codewithsk looks like you were able to merge? anything I need to do?

**Comment by codewithsk** [comment]
@laurenyu I checked out the merge conflict. It was super minor so fixed it myself and merged.

**Comment by laurenyu** [comment]
great, thanks!

**Pull request merged**
