### PR TITLE
change: update SageMaker Containers to v 2.5.3

### PR DESCRIPTION
**Pull request by mvsusp**
*Description of changes:*
- Update SageMaker Containers to version 2.5.3

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://8teunz1x41.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=3442d71f-17e3-4296-8c90-afcf5b1a7473%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://8teunz1x41.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=212f0cd8-8f74-4fd4-bd05-95f4e7faf4ac%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://8teunz1x41.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=854e8ed0-4001-4d5d-8bf2-80fafcb5a56c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jesterhazy** [comment]
### AWS CodeBuild CI Report

* Result: FAILED
* [Build Logs](https://8teunz1x41.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0a0bb685-4a25-43cd-b2c8-76c50b81fc5f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by laurenyu** [comment]
closing due to inactivity (and because script-mode was merged into master)

**Pull request closed without merging**
